server:
  port: 8808
spring:
  datasource:
    url: jdbc:mysql://localhost:1244/e-commerce?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false

